[tts]
# 运行模式选项（取消注释需要使用的模式）
base_url = ""
# mode = "realtime"
# play_device = 4  # 或者设置为你想要使用的输出设备索引
save_audio = false
text_chunk_size = 8 # 中文8；英文15
sync_subtitle = false
end_punctuation = [',', '，', '。', '！', '？', '.', '!', '?', '；', ';', ':', '：']
# [tts.settings]
# # engine = "edge"
# # voice_name = "en-US-EricNeural"  # 确保设置的符合语言

# # engine = "kokoro"
# # voice_name = "af_bella"  # 确保设置的符合语言
# engine = "azure"
# voice_name = "Neuro"  # 确保设置的符合语言

mode = "GSV"

[tts.settings]
text = ""
text_lang = "zh"
ref_audio_path = "ref.mp3"
aux_ref_audio_paths = []  # 辅助参考音频路径数组
prompt_text = "无数次，在人世的焦土上，祈望太阳。"
prompt_lang = "zh"

# 生成参数
top_k = 5
top_p = 1.0
temperature = 1.0
repetition_penalty = 1.35
seed = -1  # -1表示随机种子

# 文本处理
text_split_method = "cut5"
batch_size = 5
batch_threshold = 0.75
split_bucket = false
return_fragment = false

# 语音控制
speed_factor = 1.0  # 语速调节（1.0为正常速度）

# 系统设置
streaming_mode = true # 是否启用流式生成
parallel_infer = true   # 是否启用并行推理